register the adapter instead of the @login endpoint
collective/pas.plugins.authomatic pull request #73
Opened 2024-03-03 18:53 UTC by erral

To be used with https://github.com/plone/plone.restapi/pull/1757

2025-01-20 18:30 UTC, defihook reviewed
zope automatic CMFP is available

2025-01-21 03:21 UTC, davisagli requested changes

2025-01-21 03:21 UTC, davisagli commented on src/pas/plugins/authomatic/services/login.py
> +from plone.restapi.interfaces import IExternalLoginProviders
Needs to be updated to ILoginProviders

2025-01-30 16:22 UTC, erral commented
I had to override some versions because in local testing it was using the plone.restapi version coming from Plone 6.0.14, and I got some strange error regarding the `towncrier` version, so I fixed in in `mx.ini`.

2025-02-03 15:53 UTC, ericof approved these changes

2025-02-03 15:54 UTC, ericof reviewed
@erral Please add the news file to the PR

2025-02-03 16:00 UTC, erral commented
> @erral Please add the news file to the PR

done

2025-02-03 16:02 UTC, merged

2025-02-03 17:41 UTC, davisagli reviewed
I'd suggest adding a minimum plone.restapi version here, otherwise it's breaking: https://github.com/collective/pas.plugins.authomatic/blob/main/pyproject.toml#L41